#
# Module manifest for module 'VPDLX'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 05.04.2026
# Last Updated: 17.04.2026 (v1.02.06)
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VPDLX.psm1'

# Version number of this module.
ModuleVersion = '1.02.06'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'ce27e471-2df3-4c70-aebb-400daa67c5ce'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani (a.k.a. M.Sczepanski). All rights reserved.'

# Description of the functionality provided by this module
Description = @'
VPDLX - Virtual PowerShell Data-Logger eXtension.

A fully class-based virtual logging system that allows callers to create,
manage, and query multiple in-memory log files simultaneously without touching
the filesystem, and export them to disk in multiple formats when needed.

Architecture (v1.02.06):

  Classes (all in Classes\VPDLXClasses.ps1, type accelerators registered on load):
    [Logfile]     - core user-facing class
                    Write, Print, Read, GetAllEntries, FilterByLevel,
                    Reset, Destroy, Info/Debug/Verbose/Trace/Warning/
                    Error/Critical/Fatal shortcut methods
                    Configurable minimum log level via constructor overload
    [FileDetails] - metadata companion per Logfile instance
                    creation time, last update, last access type, axcount
    [FileStorage] - central registry for all active Logfile instances
                    Contains, Get, Count, GetNames, DestroyAll

  Public Wrapper Functions:
    VPDLXnewlogfile    - create a new virtual log file
    VPDLXislogfile     - check whether a named log file exists
    VPDLXdroplogfile   - permanently delete a named log file
    VPDLXreadlogfile   - read a specific line from a log file
    VPDLXwritelogfile  - append a new entry to a log file
    VPDLXexportlogfile - export a log file to disk (txt/log/csv/json/html/ndjson)
    VPDLXgetalllogfiles - list all active log files with metadata (v1.02.05)
    VPDLXresetlogfile   - clear all entries from a log file (v1.02.05)
    VPDLXfilterlogfile  - filter log entries by level (v1.02.05)

  Infrastructure:
    VPDLXcore          - controlled read-only accessor for module-scope vars

All three classes are registered as TypeAccelerators on module load, so:
    $log = [Logfile]::new(''MyLog'')
    $log = [Logfile]::new(''ProdLog'', ''warning'')   # with min-level filter
works immediately after a standard Import-Module call without ''using module''.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# VPDLX.Precheck.ps1 validates that the PowerShell environment meets the minimum requirements
# (PS 5.1+) before the root module is loaded. If the check fails, it emits a clear error and
# prevents the module from loading with cryptic parse errors.
#
# NEW v1.02.04 (Priorität 9): ScriptsToProcess activated with VPDLX.Precheck.ps1.
ScriptsToProcess = @('VPDLX.Precheck.ps1')

# Functions to export from this module.
#
# IMPORTANT (Issue #5 fix, v1.02.03):
#   This manifest is the SINGLE SOURCE OF TRUTH for exported functions.
#   When a module manifest (.psd1) is present and FunctionsToExport is set to
#   an explicit list, PowerShell uses it as the authoritative filter and
#   silently ignores any Export-ModuleMember call in the .psm1.
#   The Export-ModuleMember call in VPDLX.psm1 Section 7 has been removed.
#
#   --> When adding a new Public function, add its name HERE.
#
# Note: PowerShell classes are NOT exported here - they are made globally available
# via TypeAccelerators registered in VPDLX.psm1 at load time.
FunctionsToExport = @(
    # Infrastructure accessor (controlled read-only access to module-scoped variables)
    'VPDLXcore',

    # ── Public Wrapper Layer (v1.01.02) ─────────────────────────────────────
    # Logfile lifecycle management
    'VPDLXnewlogfile',      # Create a new virtual log file
    'VPDLXislogfile',       # Check whether a named log file exists
    'VPDLXdroplogfile',     # Permanently delete a named log file and all its data

    # Logfile I/O
    'VPDLXreadlogfile',     # Read a specific line from a log file (1-based, clamped)
    'VPDLXwritelogfile',    # Append a new formatted entry to a log file

    # Logfile export
    'VPDLXexportlogfile',   # Export a virtual log file to disk (txt / log / csv / json / html / ndjson)

    # ── New Public Wrapper functions (v1.02.05 - Priorität 10) ───────────
    'VPDLXgetalllogfiles',  # List all active log files with metadata summary
    'VPDLXresetlogfile',    # Clear all entries from a log file (preserves registration)
    'VPDLXfilterlogfile'   # Filter log entries by level, return structured result

    # ── Add new Public Wrapper function names below this line ──────────────
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
# FIX v1.02.03 (Issue #9):
#   Three separate class files replaced by single consolidated VPDLXClasses.ps1.
# NEW v1.02.04: Added VPDLX.Precheck.ps1
FileList = @(
    'VPDLX.psm1',
    'VPDLX.psd1',
    'VPDLX.Precheck.ps1',
    'Classes\VPDLXClasses.ps1',
    'Private\VPDLXreturn.ps1',
    'Public\VPDLXnewlogfile.ps1',
    'Public\VPDLXislogfile.ps1',
    'Public\VPDLXdroplogfile.ps1',
    'Public\VPDLXreadlogfile.ps1',
    'Public\VPDLXwritelogfile.ps1',
    'Public\VPDLXexportlogfile.ps1',
    'Public\VPDLXgetalllogfiles.ps1',
    'Public\VPDLXresetlogfile.ps1',
    'Public\VPDLXfilterlogfile.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('PowerShell', 'Windows', 'Logging', 'DataLogging', 'DataLog',
                 'VirtualLog', 'OOP', 'Classes', 'VPDLX', 'Export')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
____________________________________________________________________
‼ PLEASE VISIT THE GITHUB REPO FOR DETAILED RELEASENOTES/CHANGELOG ‼
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

v1.00.00  (05.04.2026)
----------------------
Initial release - function-based virtual log file management.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}