#
# Module manifest for module 'PSxFramework'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 01/02/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSxFramework.psm1'

# Version number of this module.
ModuleVersion = '1.00.00'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell framework for PSx Composer - provides core functionality for creating PowerShell executables using SFX modules and advanced packaging features'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'WriteLogMessage',
    'GetInstallDir',
    'VerifyBinary',
    'CreateHiddenTempData',
    'CleanHiddenTempData',
    'RemoveHiddenTempData',
    'PrepareSFX',
    'PrepareCFG',
    'PrepareDataBundle',
    'CreateDataBundle',
    'CreateChecksum',
    'CreateRelease'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'PSxFramework.psm1',
    'PSxFramework.psd1',
    'Private\OPSreturn.ps1',
    'Public\WriteLogMessage.ps1',
    'Public\GetInstallDir.ps1',
    'Public\VerifyBinary.ps1',
    'Public\CreateHiddenTempData.ps1',
    'Public\CleanHiddenTempData.ps1',
    'Public\RemoveHiddenTempData.ps1',
    'Public\PrepareSFX.ps1',
    'Public\PrepareCFG.ps1',
    'Public\PrepareDataBundle.ps1',
    'Public\CreateDataBundle.ps1',
    'Public\CreateChecksum.ps1',
    'Public\CreateRelease.ps1',
    'README.md'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PowerShell', 'Compiler', 'SFX', 'Executable', 'Packaging', 'PSxComposer', '7zip', 'Checksum')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 1.00.00 (Initial Release)
================================
- WriteLogMessage: Advanced logging function with timestamp and severity flags
- GetInstallDir: Retrieves PSx Composer installation directory from registry
- VerifyBinary: Verifies existence of executable files at specified paths
- CreateHiddenTempData: Creates hidden temporary data directory for build process
- CleanHiddenTempData: Cleans temporary data directory while preserving structure
- RemoveHiddenTempData: Completely removes temporary data directory
- PrepareSFX: Prepares SFX modules for archive creation
- PrepareCFG: Prepares and customizes SFX configuration files
- PrepareDataBundle: Prepares application data for packaging into archives
- CreateDataBundle: Creates 7z archives with configurable compression levels
- CreateChecksum: Generates SHA256/SHA512 checksums for file integrity verification
- CreateRelease: Combines SFX module, config, and archive into final executable
- Comprehensive error handling with standardized return objects
- Full English documentation and code comments
- Compatible with PowerShell 5.1+ and PowerShell Core
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
