#
# Module manifest for module 'local.httpserver'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 15.04.2026
# Last Updated: 26.04.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'local.httpserver.psm1'

# Version number of this module.
ModuleVersion = '1.00.00'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '0ed07e16-2b9b-483d-8603-1c0949fb4e33'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani (a.k.a. M.Sczepanski). All rights reserved.'

# Description of the functionality provided by this module
Description = @'
local.httpserver is a Standalone PowerShell Module that provides a local HTTP Server
(based on the .NET HTTP listener). This Server runs silently in the background and can be
managed via config-routes. It is designed to be used as a lightweight backend.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# system.precheck.ps1 validates that the PowerShell environment meets the minimum requirements
# (PS 5.1+) before the root module is loaded. If the check fails, it emits a clear error and
# prevents the module from loading with cryptic parse errors.
#
# ScriptsToProcess activated with system.precheck.ps1.
ScriptsToProcess = @('include\system.precheck.ps1')

# ____________________________________________________________________________________________________
# → INFORMATION: THIS IS THE ONLY PLACE TO DEFINE, WHICH FUNCTIONS ARE EXPORTED FROM THIS MODULE ‼
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
# Functions to export from this module.
FunctionsToExport = @(
    'SetCoreConfig',        # ← This one is important. Without it, we're not able to configure the module
    'Start-HTTPserver',
    'Stop-LocalHttpServer',
    'Get-LocalHttpServerStatus',
    'Restart-LocalHttpServer',
    'ExportServerLog',       # Export the server log to a specified path (public function)
    'GetMimeType'            # Retrieve MIME type based on file extension (public function)
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'local.httpserver.psm1',
    'local.httpserver.psd1',
    'local.httpserver.ps1',   # ← This ... Ladies and Gentlemen, is our HTTP Server
    'README.md',
    'CHANGELOG.md',
    'LICENSE',
    'NOTICE',
    # Private (internal) functions
    'Private\ReadJSON.ps1',
    'Private\Invoke-RequestHandler.ps1',
    'Private\Invoke-RouteHandler.ps1',
    'Private\New-ManagedRunspace.ps1',
    'Private\Set-RunspaceVariable.ps1',
    'Private\Get-RunspaceVariable.ps1',
    'Private\New-RunspaceJob.ps1',
    'Private\Get-RunspaceStatus.ps1',
    'Private\Stop-ManagedRunspace.ps1',
    'Private\Test-RunspaceExists.ps1',
    'Private\Invoke-RunspaceFunctionInjection.ps1',
    'Private\ServerStatusFile.ps1',
    'Private\Start-HttpRunspace.ps1',
    'Private\Invoke-ConsoleControl.ps1',
    # Public functions
    'Public\ExportServerLog.ps1',
    'Public\GetMimeType.ps1',
    'Public\Start-HTTPserver.ps1',
    'Public\Stop-LocalHttpServer.ps1',
    'Public\Get-LocalHttpServerStatus.ps1',
    'Public\Restart-LocalHttpServer.ps1',
    # Additional scripts
    'include\system.precheck.ps1',
    'include\module.config'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('PowerShell', 'Windows', 'http', 'Localhost', 'Server', 'host', 'httpserver', 'webserver')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
____________________________________________________________________
‼ PLEASE VISIT THE GITHUB REPO FOR DETAILED RELEASENOTES/CHANGELOG ‼
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

v1.00.00  (15.04.2026)
----------------------
→ Initial release (⌐■_■)
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}