#
# Module manifest for module 'OPSreturn'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 17.04.2026
# Last Updated: 17.04.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'OPSreturn.psm1'

# Version number of this module.
ModuleVersion = '1.00.00'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
# ‼ IMPORTANT INFORMATION ‼
# → DON'T FORGET TO CREATE A NEW GUID EACH TIME YOU'RE USING THIS TEMPLATE. YOU CAN DO THIS BY
# SIMPLY USING THE FOLLOWING COMMAND DIRECTLY IN POWERSHELL:  [guid]::NewGuid()
# ____________________________________________________________________________________________________
GUID = '89894b3d-02bc-4c2c-8717-a791a71589ad'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani (a.k.a. M.Sczepanski). All rights reserved.'

# Description of the functionality provided by this module
Description = @'
The OPSreturn Module creates a consistent PSCustomObject for returning operation
status information across all module functions. It provides a uniform interface for
success/failure reporting with optional data payload and other options/features.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
#ScriptsToProcess = @('PATH\TO\YOUR_SCRIPT.ps1')

# ____________________________________________________________________________________________________
# → INFORMATION: THIS IS THE ONLY PLACE TO DEFINE, WHICH FUNCTIONS ARE EXPORTED FROM THIS MODULE ‼
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
# Functions to export from this module.
FunctionsToExport = @(
    'SetCoreConfig',        # ← This one is important. Without it, we're not able to configure the module
    'OPSsuccess',
    'OPSinfo',
    'OPSdebug',
    'OPStimeout',
    'OPSwarn',
    'OPSfail',
    'OPSerror',
    'OPScritical',
    'OPSfatal'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'OPSreturn.psm1',
    'OPSreturn.psd1',
    # Private (internal) functions
    'Private\OPSreturn.ps1',
    # Public functions
    'Public\OPSsuccess.ps1',
    'Public\OPSinfo.ps1',
    'Public\OPSdebug.ps1',
    'Public\OPStimeout.ps1',
    'Public\OPSwarn.ps1',
    'Public\OPSfail.ps1',
    'Public\OPSerror.ps1',
    'Public\OPScritical.ps1',
    'Public\OPSfatal.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('PowerShell')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
____________________________________________________________________
‼ PLEASE VISIT THE GITHUB REPO FOR DETAILED RELEASENOTES/CHANGELOG ‼
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

v1.00.00  (17.04.2026)
----------------------
→ Initial release (⌐■_■)
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}