#
# Module manifest for module 'WinISO.ScriptFXLib'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 28.03.2026
# Last Updated: 04.04.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WinISO.ScriptFXLib.psm1'

# Version number of this module.
ModuleVersion = '1.00.05'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'c132d370-40ae-4dd6-9541-7e27bfb28833'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powerfull Module for downloading, customizing and re-building bootable Windows 11 Pro Setup ISO Files.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
        # Core / Infrastructure
        'AppScope',
        'InitializeEnvironment',
        'VerifyEnvironment',
        'CheckModuleRequirements',
        'WinISOcore',

        # Logging
        'WriteLogMessage',

        # Download helpers
        'GitHubDownload',
        'GetLatestPowerShellSetup',

        # UUP Dump workflow
        'DownloadUUPDump',
        'GetUUPDumpPackage',
        'ExtractUUPDump',
        'CreateUUPDiso',
        'CleanupUUPDump',
        'RenameUUPDiso',
        'ExtractUUPDiso',

        # WIM image operations
        'ImageIndexLookup',
        'MountWIMimage',
        'UnMountWIMimage',

        # Registry Hive Operations
        'LoadRegistryHive',
        'UnloadRegistryHive',
        'RegistryHiveAdd',
        'RegistryHiveRem',
        'RegistryHiveImport',
        'RegistryHiveExport',
        'RegistryHiveQuery',

        # Appx / MSIX Package Operations
        'GetAppxPackages',
        'RemAppxPackages',
        'AddAppxPackages',
        'AppxPackageLookUp'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'WinISO.ScriptFXLib.psm1',
    'WinISO.ScriptFXLib.psd1',
    'README.md',

    # Private
    'Private\OPSreturn.ps1',
    'Private\Invoke-UUPRuntimeLog.ps1',
    'Private\Get-UUPLogTail.ps1',
    'Private\Test-UUPConversionPhase.ps1',
    'Private\Invoke-UUPProcessKill.ps1',
    'Private\Get-UUPNewestISO.ps1',
    'Private\ValidateRegFile.ps1',

    # Public
    'Public\AppScope.ps1',
    'Public\InitializeEnvironment.ps1',
    'Public\VerifyEnvironment.ps1',
    'Public\CheckModuleRequirements.ps1',
    'Public\WinISOcore.ps1',
    'Public\WriteLogMessage.ps1',
    'Public\GetLatestPowerShellSetup.ps1',
    'Public\GitHubDownload.ps1',
    'Public\DownloadUUPDump.ps1',
    'Public\GetUUPDumpPackage.ps1',
    'Public\ExtractUUPDump.ps1',
    'Public\CreateUUPDiso.ps1',
    'Public\CleanupUUPDump.ps1',
    'Public\RenameUUPDiso.ps1',
    'Public\ExtractUUPDiso.ps1',
    'Public\ImageIndexLookup.ps1',
    'Public\MountWIMimage.ps1',
    'Public\UnMountWIMimage.ps1',
    'Public\LoadRegistryHive.ps1',
    'Public\UnloadRegistryHive.ps1',
    'Public\RegistryHiveAdd.ps1',
    'Public\RegistryHiveRem.ps1',
    'Public\RegistryHiveImport.ps1',
    'Public\RegistryHiveExport.ps1',
    'Public\RegistryHiveQuery.ps1',
    'Public\GetAppxPackages.ps1',
    'Public\RemAppxPackages.ps1',
    'Public\AddAppxPackages.ps1',
    'Public\AppxPackageLookUp.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PowerShell', 'DISM', 'Windows11', 'ISO', 'WindowsSetup', 'SkipOOBE', 'Unattended', 'autounattend', 'UnattendedInstallation', 'UnattendedSetup', 'Customization', 'UUPDump', 'WinISO', 'AppxPackage', 'MSIX', 'ProvisionedPackage')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
v1.00.05
‾‾‾‾‾‾‾‾‾‾
WinISOcore:               Extended with full read/write support for $script:appverify and $script:appx.
                          appverify keys: PASS/FAIL/INFO/WARN status strings + 'result' sub-hashtable.
                          appx keys: 'listed', 'remove', 'inject' array replacement.
CheckModuleRequirements:  Redesigned check status schema: PASS / FAIL / INFO / WARN.
                          INFO = resolvable automatically (e.g. via InitializeEnvironment).
                          WARN = requires manual user action (e.g. re-run elevated, upgrade PS).
                          FAIL = no known automated fix (hard system component missing).
                          All check results now written into $script:appverify via WinISOcore.
                          Result counters (pass/fail/info/warn) written to $script:appverify['result'].
                          Overall function succeeds (code 0) if no FAIL exists (PASS+INFO+WARN = ok).
                          Export report updated to reflect new 4-state schema.
DownloadUUPDump:          New -Edition parameter ('Pro'/'Home') with UUPDump ID mapping.
                          New -IncludeNetFX / -ExcludeNetFX mutually exclusive switches (default: NetFX included).
                          New -UseESD switch for install.esd instead of install.wim (default: WIM).
                          BUGFIX: $script:uupdump['buildno'] now stores actual build number (e.g. 26100.3476)
                          instead of UUID (was incorrect in previous version).
                          BUGFIX: cleanup POST param corrected to '0' (was incorrectly '1').
                          Full $script:uupdump write-back on success: ostype/osvers/osarch/edition/
                          buildno/kbsize/zipname. multiedition field explicitly cleared.
                          Returns error if any WinISOcore write operation fails (hard guarantee).
GetUUPDumpPackage:        NEW function for multi-edition / Virtual Editions download (autodl=3).
                          -Editions array parameter: ProWorkstations, ProEducation, Education,
                          Enterprise, IoTEnterprise (one or more, deduplicated automatically).
                          Semicolon-separated UUP edition IDs in GET URL; autodl=3 in POST body.
                          Same NetFX/ESD/BuildNo/OSvers/OSarch/Target parameters as DownloadUUPDump.
                          $script:uupdump['multiedition'] stores semicolon-joined display names.
                          $script:uupdump['edition'] is cleared (empty) for multi-edition packages.
GetAppxPackages:          NEW function. Lists all provisioned Appx packages from a mounted WIM image.
                          Uses Get-AppxProvisionedPackage (DISM PowerShell module).
                          Results stored as array of PSCustomObjects in $script:appx['listed'].
                          Each entry: DisplayName, PackageName, Version, Architecture, PublisherId.
                          Optional file export via -ExportFile and -Format (TXT | CSV | JSON).
                          Defaults MountPoint from $script:appenv['MountPoint'].
RemAppxPackages:          NEW function. Removes provisioned Appx packages from a mounted WIM image.
                          Processes all entries in $script:appx['remove'] via DISM.exe
                          /Remove-ProvisionedAppxPackage.
                          Supports .appx, .appxbundle, .msix, .msixbundle and provisioned PackageNames.
                          Monitoring: successfully removed packages are deleted from $script:appx['remove'].
                          Failed packages remain in $script:appx['remove'] for inspection.
                          -ContinueOnError switch to process all packages despite individual failures.
                          Returns @{ Succeeded=[array]; Failed=[array] } as .data.
AddAppxPackages:          NEW function. Injects provisioned Appx packages into a mounted WIM image.
                          Processes all entries in $script:appx['inject'] via DISM.exe
                          /Add-ProvisionedAppxPackage.
                          Supports .appx, .appxbundle, .msix, .msixbundle from $script:appenv['AppxBundle'].
                          Optional per-entry license file via LicenseFile property; falls back to /SkipLicense.
                          Monitoring: successfully injected packages are deleted from $script:appx['inject'].
                          Failed packages remain in $script:appx['inject'] for inspection.
                          -ContinueOnError switch to process all packages despite individual failures.
                          -AppxSourceDir override for custom package source directories.
                          Returns @{ Succeeded=[array]; Failed=[array] } as .data.
AppxPackageLookUp:        NEW function. Dual-mode Appx package verification helper.
                          Mode 1 (Image): Substring search in provisioned packages of a mounted WIM.
                          Uses $script:appx['listed'] cache; bypassed with -ForceRefresh.
                          Mode 2 (File): Physical file existence check in AppxBundle source directory.
                          Both modes combinable in a single call via -SearchTerm and -PackageFile.
                          Supports .appx, .appxbundle, .msix, .msixbundle in FILE mode.
                          Returns @{ ImageMatches=[array]; FileExists=[bool|null]; SearchTerm; PackageFile }.
WinISO.ScriptFXLib.psm1:  $script:appverify and $script:appx scopes added and documented.
                          Module version bumped to 1.00.05.

v1.00.04
‾‾‾‾‾‾‾‾‾‾
LoadRegistryHive:       Mounts one or all offline registry hives from the mounted WIM image into the live registry.
UnloadRegistryHive:     Unloads one or all previously loaded offline registry hives from the live registry.
RegistryHiveAdd:        Adds a new registry key and/or value to a loaded offline registry hive.
RegistryHiveRem:        Removes an existing registry key and/or value from a loaded offline registry hive.
RegistryHiveImport:     Imports a validated .reg file into a loaded offline registry hive.
RegistryHiveExport:     Exports a registry key branch from a loaded offline hive to a .reg file.
RegistryHiveQuery:      Queries registry keys and/or values from a loaded offline registry hive.
Private Helpers:        ValidateRegFile-Function (Validates that a .reg file is syntactically correct)

v1.00.03
‾‾‾‾‾‾‾‾‾‾
- GetLatestPowerShellSetup: Downloads the latest PowerShell release from GitHub and optionally installs it silently
- CreateUUPDiso:            Full ISO creation orchestration with multi-layer process monitoring
- WinISOcore:               Type-safe read/write accessor for module-scope variables
- ImageIndexLookup:         WIM image edition search returning unique ImageIndex
- MountWIMimage:            Replaces previous MountWIMimage with full validation and defensive unmount
- UnMountWIMimage:          Verified WIM dismount with commit/discard support
- CheckModuleRequirements:  System dependency audit with optional text export
- Private helpers:          Invoke-UUPRuntimeLog, Get-UUPLogTail, Test-UUPConversionPhase,
                            Invoke-UUPProcessKill, Get-UUPNewestISO

v1.00.02
‾‾‾‾‾‾‾‾‾‾
- DownloadUUPDump  : Downloads a UUPDump ZIP package from uupdump.net based on OS type, version, architecture and optional build number
- ExtractUUPDump   : Extracts a UUPDump ZIP archive to a target directory with optional integrity verification and ZIP cleanup
- CleanupUUPDump   : Cleans the UUPDump working directory, retaining only the generated ISO file
- RenameUUPDiso    : Renames the ISO file found in the UUPDump working directory to a specified name
- ExtractUUPDiso   : Mounts a UUPDump ISO image and copies all contents to a target directory

v1.00.01
‾‾‾‾‾‾‾‾‾‾
- InitializeEnvironment : Creates the full WinISO working environment directory structure
- VerifyEnvironment     : Verifies all required WinISO environment directories exist
- GitHubDownload        : Generic GitHub asset downloader with version resolution
- WriteLogMessage       : Structured log writer with timestamp and severity flags
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
