#
# Module manifest for module 'VPDLX'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 05.04.2026
# Last Updated: 11.04.2026 (v1.02.06)
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VPDLX.psm1'

# Version number of this module.
ModuleVersion = '1.02.06'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'ce27e471-2df3-4c70-aebb-400daa67c5ce'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani (a.k.a. M.Sczepanski). All rights reserved.'

# Description of the functionality provided by this module
Description = @'
VPDLX - Virtual PowerShell Data-Logger eXtension.

A fully class-based virtual logging system that allows callers to create,
manage, and query multiple in-memory log files simultaneously without touching
the filesystem, and export them to disk in multiple formats when needed.

Architecture (v1.02.06):

  Classes (all in Classes\VPDLXClasses.ps1, type accelerators registered on load):
    [Logfile]     - core user-facing class
                    Write, Print, Read, GetAllEntries, FilterByLevel,
                    Reset, Destroy, Info/Debug/Verbose/Trace/Warning/
                    Error/Critical/Fatal shortcut methods
                    Configurable minimum log level via constructor overload
    [FileDetails] - metadata companion per Logfile instance
                    creation time, last update, last access type, axcount
    [FileStorage] - central registry for all active Logfile instances
                    Contains, Get, Count, GetNames, DestroyAll

  Public Wrapper Functions:
    VPDLXnewlogfile    - create a new virtual log file
    VPDLXislogfile     - check whether a named log file exists
    VPDLXdroplogfile   - permanently delete a named log file
    VPDLXreadlogfile   - read a specific line from a log file
    VPDLXwritelogfile  - append a new entry to a log file
    VPDLXexportlogfile - export a log file to disk (txt/log/csv/json/html/ndjson)
    VPDLXgetalllogfiles - list all active log files with metadata (v1.02.05)
    VPDLXresetlogfile   - clear all entries from a log file (v1.02.05)
    VPDLXfilterlogfile  - filter log entries by level (v1.02.05)

  Infrastructure:
    VPDLXcore          - controlled read-only accessor for module-scope vars

All three classes are registered as TypeAccelerators on module load, so:
    $log = [Logfile]::new(''MyLog'')
    $log = [Logfile]::new(''ProdLog'', ''warning'')   # with min-level filter
works immediately after a standard Import-Module call without ''using module''.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# VPDLX.Precheck.ps1 validates that the PowerShell environment meets the minimum requirements
# (PS 5.1+) before the root module is loaded. If the check fails, it emits a clear error and
# prevents the module from loading with cryptic parse errors.
#
# NEW v1.02.04 (Priorität 9): ScriptsToProcess activated with VPDLX.Precheck.ps1.
ScriptsToProcess = @('VPDLX.Precheck.ps1')

# Functions to export from this module.
#
# IMPORTANT (Issue #5 fix, v1.02.03):
#   This manifest is the SINGLE SOURCE OF TRUTH for exported functions.
#   When a module manifest (.psd1) is present and FunctionsToExport is set to
#   an explicit list, PowerShell uses it as the authoritative filter and
#   silently ignores any Export-ModuleMember call in the .psm1.
#   The Export-ModuleMember call in VPDLX.psm1 Section 7 has been removed.
#
#   --> When adding a new Public function, add its name HERE.
#
# Note: PowerShell classes are NOT exported here — they are made globally available
# via TypeAccelerators registered in VPDLX.psm1 at load time.
FunctionsToExport = @(
    # Infrastructure accessor (controlled read-only access to module-scoped variables)
    'VPDLXcore'

    # ── Public Wrapper Layer (v1.01.02) ─────────────────────────────────────
    # Logfile lifecycle management
    'VPDLXnewlogfile'      # Create a new virtual log file
    'VPDLXislogfile'       # Check whether a named log file exists
    'VPDLXdroplogfile'     # Permanently delete a named log file and all its data

    # Logfile I/O
    'VPDLXreadlogfile'     # Read a specific line from a log file (1-based, clamped)
    'VPDLXwritelogfile'    # Append a new formatted entry to a log file

    # Logfile export
    'VPDLXexportlogfile'   # Export a virtual log file to disk (txt / log / csv / json / html / ndjson)

    # ── New Public Wrapper functions (v1.02.05 — Priorität 10) ───────────
    'VPDLXgetalllogfiles'  # List all active log files with metadata summary
    'VPDLXresetlogfile'    # Clear all entries from a log file (preserves registration)
    'VPDLXfilterlogfile'   # Filter log entries by level, return structured result

    # ── Add new Public Wrapper function names below this line ──────────────
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
# FIX v1.02.03 (Issue #9):
#   Three separate class files replaced by single consolidated VPDLXClasses.ps1.
# NEW v1.02.04: Added VPDLX.Precheck.ps1
FileList = @(
    'VPDLX.psm1',
    'VPDLX.psd1',
    'VPDLX.Precheck.ps1',
    'Classes\VPDLXClasses.ps1',
    'Private\VPDLXreturn.ps1',
    'Public\VPDLXnewlogfile.ps1',
    'Public\VPDLXislogfile.ps1',
    'Public\VPDLXdroplogfile.ps1',
    'Public\VPDLXreadlogfile.ps1',
    'Public\VPDLXwritelogfile.ps1',
    'Public\VPDLXexportlogfile.ps1',
    'Public\VPDLXgetalllogfiles.ps1',
    'Public\VPDLXresetlogfile.ps1',
    'Public\VPDLXfilterlogfile.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('PowerShell', 'Windows', 'Logging', 'DataLogging', 'DataLog',
                 'VirtualLog', 'OOP', 'Classes', 'VPDLX', 'Export')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
v1.02.06  (11.04.2026)
----------------------
Advanced Features (Priorität 10 der Developer ToDo-Liste).

New:
  HTML export format (VPDLXexportlogfile -ExportAs 'html')
      Generates a self-contained HTML document with embedded CSS styling.
      Features level-specific row colouring: green text for INFO, blue for
      DEBUG, orange background for WARNING, red background for ERROR/FATAL.
      Includes a header with log file name, export timestamp, and entry
      count. Footer shows VPDLX module version. Print-friendly layout.
      All message content is HTML-encoded via
      [System.Net.WebUtility]::HtmlEncode() for XSS safety.
      Row assembly uses StringBuilder for performance.
      File extension: .html

  NDJSON export format (VPDLXexportlogfile -ExportAs 'ndjson')
      Newline-Delimited JSON — each log entry is serialised as a single
      compact JSON object on its own line using ConvertTo-Json -Compress.
      No root wrapper or array — ideal for streaming to log pipelines
      (Elasticsearch, Logstash, Kafka, AWS Kinesis, Grafana Loki).
      Each object contains Timestamp, Level, and Message properties.
      File extension: .ndjson

  Configurable minimum log level ([Logfile] constructor overload)
      New constructor: [Logfile]::new('ProdLog', 'warning') creates a
      log file that silently discards entries below the specified
      severity threshold. Severity ranking (low to high):
        trace(0) < debug(1) < verbose(2) < info(3) < warning(4)
        < error(5) < critical(6) < fatal(7)
      Write() and Print() silently return when a message's level is
      below the configured minimum — no exception, no side effects.
      New static property: [Logfile]::LevelSeverity (severity hashtable)
      New hidden fields: $_minLevelIndex (int, -1 = no filter),
        $_minLevelName (string)
      New public method: GetMinLogLevel() — returns the configured
        minimum level name or 'none' if no filter is active.
      ToString() appends '| MinLevel: <name>' when a filter is active.
      The original single-argument constructor is unchanged and creates
      log files with no minimum level filter (all entries accepted).

Changed:
  $script:export extended with 'html' (.html) and 'ndjson' (.ndjson) keys.
  VPDLXexportlogfile comment-based help updated for new formats.
  VPDLXClasses.ps1 updated with dual constructors and _InitLogfile().
  VPDLX.psm1 architecture description updated for new formats.
  Module version updated to 1.02.06 in all files.

v1.02.05  (11.04.2026)
----------------------
New Wrapper Functions & Module Statistics (Priorität 10 der Developer ToDo-Liste).

New:
  VPDLXgetalllogfiles
      Lists all active virtual log files in the current session. Returns an
      array of PSCustomObjects with Name, EntryCount, Created, Updated,
      LastAccessed, and AccessCount for each log file. Read-only operation
      that does not modify any log file state.

  VPDLXresetlogfile -Logfile <name>
      Clears all entries from a virtual log file without destroying it. The
      log file remains registered and can immediately accept new entries.
      Returns the number of entries that were cleared in .data.
      Difference from VPDLXdroplogfile: reset keeps the log alive, drop
      destroys it permanently.

  VPDLXfilterlogfile -Logfile <name> -Level <level>
      Filters the entries of a virtual log file by log level. Returns a
      structured PSCustomObject in .data with Entries (string[]), Count
      (int), and Level (string). Supports [ValidateSet] tab-completion
      for the Level parameter.

  VPDLXcore -KeyID 'stats'
      Returns module-wide statistics: ActiveLogfiles, TotalEntries,
      MaxEntries, MaxEntriesLog, MinEntries, MinEntriesLog, and
      ModuleVersion. Read-only — no log file state is modified.

v1.02.04  (11.04.2026)
----------------------
Performance & Quality improvements (Priorität 9 der Developer ToDo-Liste).

New:
  Precheck script (VPDLX.Precheck.ps1)
      Validates PowerShell >= 5.1 before the module loads. Prevents
      cryptic parse errors on older PowerShell versions. Registered
      via ScriptsToProcess in the module manifest.

  Configurable message length limit ([Logfile]::MaxMessageLength)
      ValidateMessage() now enforces a maximum message length (default:
      8192 characters). Protects against accidental memory flooding from
      extremely long strings. Configurable at runtime:
        [Logfile]::MaxMessageLength = 16384

  BOM-free UTF-8 export (-NoBOM switch on VPDLXexportlogfile)
      Forces BOM-free UTF-8 output on all PowerShell versions including
      Windows PowerShell 5.1. Essential for interoperability with
      Unix-based log aggregators, JSON parsers, and web services.
      Uses [System.Text.UTF8Encoding]::new($false) internally.

v1.02.03  (11.04.2026)
----------------------
Bugfix release: Destroy() and ToString() hardened; FilterByLevel()
call-order and label corrected; export configuration conflict resolved;
VPDLXreturn status code range extended.

Fixed:
  Destroy() — GuardDestroyed() at entry (Issue #1)
      Calling Destroy() on an already-destroyed instance now correctly
      throws ObjectDisposedException instead of silently succeeding.
      The redundant 'if ($null -ne $this._data)' check has been removed.

  Destroy() — try/catch/finally around storage.Remove() (Issue #6)
      FileStorage.Remove() may throw InvalidOperationException if the
      name is not found (e.g. due to state desynchronisation via VPDLXcore).
      The finally block now unconditionally clears _data and sets both
      _data and _details to $null, guaranteeing cleanup regardless of
      whether Remove() succeeds or throws.

  ToString() — GuardDestroyed() at entry (Issue #3)
      Calling ToString() on a destroyed instance (explicitly or via
      string interpolation) now throws ObjectDisposedException instead
      of a misleading NullReferenceException. The partial null-check
      for _data has been removed — GuardDestroyed() makes it redundant.

  FilterByLevel() — RecordFilter() call-order fix (Issue #2)
      The metadata-recording call was placed before the foreach loop.
      Moved to after the loop so metadata is recorded only on successful
      completion.

  FilterByLevel() — RecordFilter() renamed + label fix (Issue #4)
      Hidden method RecordFilter() renamed to RecordFilterByLevel().
      Label string changed from 'Filter' to 'FilterByLevel' to match
      the public method name.

  FunctionsToExport — single source of truth (Issue #5)
      Export-ModuleMember call removed from VPDLX.psm1 Section 7 (the
      manifest takes precedence). SINGLE SOURCE OF TRUTH comment block
      added to FunctionsToExport in VPDLX.psd1.

  VPDLXreturn — status code range extended (Issue #8)
      [ValidateSet(0, -1)] replaced with [ValidateRange(-99, 99)].
      Status code conventions documented: 0 = success, -1 = general
      failure, 1..99 = partial success, -2..-99 = typed errors.

  Print() — batch validation diagnostics improved (Issue #7)
      The pre-validation loop now tracks the 0-based element index.
      When validation fails, the enriched ArgumentException includes
      the index and a safe preview of the offending value (truncated
      to 40 chars, CR/LF escaped as \r/\n).

  Class consolidation — forward-reference resolved (Issue #9)
      FileDetails.ps1, FileStorage.ps1, Logfile.ps1 merged into
      Classes\VPDLXClasses.ps1. FileStorage now uses
      Dictionary[string, Logfile] instead of Dictionary[string, object].
      Get() returns [Logfile], Add() accepts [Logfile] — full type
      safety and IntelliSense support.

  DestroyAll() — batch cleanup + OnRemove integration (Issue #10)
      FileStorage.DestroyAll() iterates all registered instances,
      calls Destroy() on each (with per-instance try/catch), then
      clears the registry. OnRemove in VPDLX.psm1 now calls
      DestroyAll() before removing TypeAccelerators.
      VPDLXcore -KeyID 'destroyall' exposes batch cleanup to callers.

v1.01.02  (06.04.2026)
----------------------
Public Wrapper Layer introduced + Export functionality added.

New Public Wrapper functions (dot-sourced from Public\):
  VPDLXnewlogfile
      Creates a new virtual Logfile instance and registers it in FileStorage.
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXislogfile
      Checks whether a named log file exists in FileStorage (analog Contains).
      Returns: [bool] directly (not a result object)

  VPDLXdroplogfile
      Calls .Destroy() on the Logfile instance and removes it from storage.
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXreadlogfile
      Reads one entry by 1-based line index (clamped on out-of-range input).
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXwritelogfile
      Appends a new formatted entry to an existing log file.
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXexportlogfile
      Writes a virtual log file as a physical file on disk.
      Parameters: Logfile (mandatory), LogPath (mandatory), ExportAs (mandatory),
                  Override (optional switch — overwrites existing file).
      Supported formats: txt, log, csv, json.
      Auto-creates the target directory if it does not exist.
      Returns: VPDLXreturn object { code, msg, data }

v1.01.00  (06.04.2026)
----------------------
Full architectural rewrite: function-based design replaced by a clean
class-based OOP architecture.

New classes (all registered as TypeAccelerators):
  [Logfile]
      .Write(level, message)          - append a single formatted log entry
      .Print(level, messages[])       - append multiple entries in one call
      .Read(line)                     - retrieve a specific line (1-based, clamped)
      .GetAllEntries()                - retrieve complete log content as string[]
      .FilterByLevel(level)           - retrieve lines matching a specific log level
      .Reset()                        - clear all log data (irreversible)
      .Destroy()                      - unregister and dispose the instance
      .Info/Debug/Verbose/Trace/Warning/Error/Critical/Fatal(msg)  - shortcut write methods
      .GetDetails()                   - access the [FileDetails] companion object
      .IsEmpty()                      - returns $true if no entries exist
      .HasEntries()                   - returns $true if at least one entry exists
      .EntryCount()                   - returns the current number of entries

  [FileDetails]
      .GetCreated()                   - creation timestamp
      .GetUpdated()                   - last write/reset timestamp
      .GetLastAccessed()              - last read/filter timestamp
      .GetLastAccessType()            - type of the most recent interaction
      .GetEntries()                   - current entry count
      .GetAxcount()                   - total interaction counter since creation
      .ToHashtable()                  - all metadata as an ordered hashtable

  [FileStorage]
      .Contains(name)                 - check if a logfile name is registered
      .Get(name)                      - retrieve a Logfile instance by name
      .Count()                        - number of registered instances
      .GetNames()                     - array of all registered names

Infrastructure:
  VPDLXcore -KeyID appinfo            - module metadata hashtable
  VPDLXcore -KeyID storage            - [FileStorage] singleton
  VPDLXcore -KeyID export             - export format definitions (txt, csv, json, log)

Bugfix:
  Renamed Filter() -> FilterByLevel() in [Logfile].
  ''filter'' is a reserved PowerShell keyword that caused a parser error
  preventing the class file from loading.

Removed (replaced by class methods):
  CreateNewLogfile, WriteLogfileEntry, ReadLogfileEntry, ResetLogfile, DeleteLogfile

v1.00.00  (05.04.2026)
----------------------
Initial release - function-based virtual log file management.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}