#
# Module manifest for module 'VPDLX'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 05.04.2026
# Last Updated: 11.04.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VPDLX.psm1'

# Version number of this module.
ModuleVersion = '1.02.03'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'ce27e471-2df3-4c70-aebb-400daa67c5ce'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani (a.k.a. M.Sczepanski). All rights reserved.'

# Description of the functionality provided by this module
Description = @'
VPDLX - Virtual PowerShell Data-Logger eXtension.

A fully class-based virtual logging system that allows callers to create,
manage, and query multiple in-memory log files simultaneously without touching
the filesystem, and export them to disk in multiple formats when needed.

Architecture (v1.02.03):

  Classes (type accelerators registered on load):
    [Logfile]     - core user-facing class
                    Write, Print, Read, GetAllEntries, FilterByLevel,
                    Reset, Destroy, Info/Debug/Verbose/Trace/Warning/
                    Error/Critical/Fatal shortcut methods
    [FileDetails] - metadata companion per Logfile instance
                    creation time, last update, last access type, axcount
    [FileStorage] - central registry for all active Logfile instances
                    Contains, Get, Count, GetNames

  Public Wrapper Functions (v1.01.02):
    VPDLXnewlogfile    - create a new virtual log file
    VPDLXislogfile     - check whether a named log file exists
    VPDLXdroplogfile   - permanently delete a named log file
    VPDLXreadlogfile   - read a specific line from a log file
    VPDLXwritelogfile  - append a new entry to a log file
    VPDLXexportlogfile - export a virtual log file to disk (txt/log/csv/json)

  Infrastructure:
    VPDLXcore          - controlled read-only accessor for module-scope vars

All three classes are registered as TypeAccelerators on module load, so:
    $log = [Logfile]::new(''MyLog'')
works immediately after a standard Import-Module call without ''using module''.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# Not used — class loading is handled directly in VPDLX.psm1 to ensure correct load order.
# ScriptsToProcess = @()

# Functions to export from this module.
# Note: PowerShell classes are NOT exported here — they are made globally available
# via TypeAccelerators registered in VPDLX.psm1 at load time.
FunctionsToExport = @(
    # Infrastructure accessor (controlled read-only access to module-scoped variables)
    'VPDLXcore'

    # ── Public Wrapper Layer (v1.01.02) ─────────────────────────────────────
    # Logfile lifecycle management
    'VPDLXnewlogfile'      # Create a new virtual log file
    'VPDLXislogfile'       # Check whether a named log file exists
    'VPDLXdroplogfile'     # Permanently delete a named log file and all its data

    # Logfile I/O
    'VPDLXreadlogfile'     # Read a specific line from a log file (1-based, clamped)
    'VPDLXwritelogfile'    # Append a new formatted entry to a log file

    # Logfile export
    'VPDLXexportlogfile'   # Export a virtual log file to disk (txt / log / csv / json)
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'VPDLX.psm1',
    'VPDLX.psd1',
    'Classes\FileDetails.ps1',
    'Classes\FileStorage.ps1',
    'Classes\Logfile.ps1',
    'Private\VPDLXreturn.ps1',
    'Public\VPDLXnewlogfile.ps1',
    'Public\VPDLXislogfile.ps1',
    'Public\VPDLXdroplogfile.ps1',
    'Public\VPDLXreadlogfile.ps1',
    'Public\VPDLXwritelogfile.ps1',
    'Public\VPDLXexportlogfile.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('PowerShell', 'Windows', 'Logging', 'DataLogging', 'DataLog',
                 'VirtualLog', 'OOP', 'Classes', 'VPDLX', 'Export')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
v1.02.03  (11.04.2026)
----------------------
Bugfix release: Destroy() and ToString() hardened.

Fixed:
  Destroy() — GuardDestroyed() at entry (Issue #1)
      Calling Destroy() on an already-destroyed instance now correctly
      throws ObjectDisposedException instead of silently succeeding.
      The redundant 'if ($null -ne $this._data)' check has been removed.

  Destroy() — try/catch/finally around storage.Remove() (Issue #6)
      FileStorage.Remove() may throw InvalidOperationException if the
      name is not found (e.g. due to state desynchronisation via VPDLXcore).
      The finally block now unconditionally clears _data and sets both
      _data and _details to $null, guaranteeing cleanup regardless of
      whether Remove() succeeds or throws.

  ToString() — GuardDestroyed() at entry (Issue #3)
      Calling ToString() on a destroyed instance (explicitly or via
      string interpolation) now throws ObjectDisposedException instead
      of a misleading NullReferenceException. The partial null-check
      for _data has been removed — GuardDestroyed() makes it redundant.

v1.01.02  (06.04.2026)
----------------------
Public Wrapper Layer introduced + Export functionality added.

New Public Wrapper functions (dot-sourced from Public\):
  VPDLXnewlogfile
      Creates a new virtual Logfile instance and registers it in FileStorage.
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXislogfile
      Checks whether a named log file exists in FileStorage (analog Contains).
      Returns: [bool] directly (not a result object)

  VPDLXdroplogfile
      Calls .Destroy() on the Logfile instance and removes it from storage.
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXreadlogfile
      Reads one entry by 1-based line index (clamped on out-of-range input).
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXwritelogfile
      Appends a new formatted entry to an existing log file.
      Returns: VPDLXreturn object { code, msg, data }

  VPDLXexportlogfile
      Writes a virtual log file as a physical file on disk.
      Parameters: Logfile (mandatory), LogPath (mandatory), ExportAs (mandatory),
                  Override (optional switch — overwrites existing file).
      Supported formats: txt, log, csv, json.
      Auto-creates the target directory if it does not exist.
      Returns: VPDLXreturn object { code, msg, data }

v1.01.00  (06.04.2026)
----------------------
Full architectural rewrite: function-based design replaced by a clean
class-based OOP architecture.

New classes (all registered as TypeAccelerators):
  [Logfile]
      .Write(level, message)          - append a single formatted log entry
      .Print(level, messages[])       - append multiple entries in one call
      .Read(line)                     - retrieve a specific line (1-based, clamped)
      .GetAllEntries()                - retrieve complete log content as string[]
      .FilterByLevel(level)           - retrieve lines matching a specific log level
      .Reset()                        - clear all log data (irreversible)
      .Destroy()                      - unregister and dispose the instance
      .Info/Debug/Verbose/Trace/Warning/Error/Critical/Fatal(msg)  - shortcut write methods
      .GetDetails()                   - access the [FileDetails] companion object
      .IsEmpty()                      - returns $true if no entries exist
      .HasEntries()                   - returns $true if at least one entry exists
      .EntryCount()                   - returns the current number of entries

  [FileDetails]
      .GetCreated()                   - creation timestamp
      .GetUpdated()                   - last write/reset timestamp
      .GetLastAccessed()              - last read/filter timestamp
      .GetLastAccessType()            - type of the most recent interaction
      .GetEntries()                   - current entry count
      .GetAxcount()                   - total interaction counter since creation
      .ToHashtable()                  - all metadata as an ordered hashtable

  [FileStorage]
      .Contains(name)                 - check if a logfile name is registered
      .Get(name)                      - retrieve a Logfile instance by name
      .Count()                        - number of registered instances
      .GetNames()                     - array of all registered names

Infrastructure:
  VPDLXcore -KeyID appinfo            - module metadata hashtable
  VPDLXcore -KeyID storage            - [FileStorage] singleton
  VPDLXcore -KeyID export             - export format definitions (txt, csv, json, log)

Bugfix:
  Renamed Filter() -> FilterByLevel() in [Logfile].
  ''filter'' is a reserved PowerShell keyword that caused a parser error
  preventing the class file from loading.

Removed (replaced by class methods):
  CreateNewLogfile, WriteLogfileEntry, ReadLogfileEntry, ResetLogfile, DeleteLogfile

v1.00.00  (05.04.2026)
----------------------
Initial release - function-based virtual log file management.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
