#
# Module manifest for module 'VPDLX'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 05.04.2026
# Last Updated: 06.04.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VPDLX.psm1'

# Version number of this module.
ModuleVersion = '1.01.00'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'ce27e471-2df3-4c70-aebb-400daa67c5ce'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2026 Praetoriani. All rights reserved.'

# Description of the functionality provided by this module
Description = @'
VPDLX - Virtual PowerShell Data-Logger eXtension.

A fully class-based virtual logging system that allows callers to create,
manage, and query multiple in-memory log files simultaneously without touching
the filesystem.

v1.01.00 introduces a clean OOP architecture with three exportable classes:
  [Logfile]     - core user-facing class (Write, Print, Read, SoakUp, FilterByLevel, Reset, Destroy)
  [FileDetails] - metadata companion (creation time, last update, last access, interaction count)
  [FileStorage] - central registry of all active Logfile instances

All three classes are registered as TypeAccelerators on module load so that
  $log = [Logfile]::new('MyLog')
works immediately after a standard Import-Module call.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# Not used — class loading is handled directly in VPDLX.psm1 to ensure correct load order.
# ScriptsToProcess = @()

# Functions to export from this module.
# Note: PowerShell classes are NOT exported here — they are made globally available
# via TypeAccelerators registered in VPDLX.psm1. See the module description above.
FunctionsToExport = @(
    # Infrastructure accessor (read-only access to module-scoped variables)
    'VPDLXcore'
    # Public wrapper functions will be listed here in future releases
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'VPDLX.psm1',
    'VPDLX.psd1',
    'Classes\FileDetails.ps1',
    'Classes\FileStorage.ps1',
    'Classes\Logfile.ps1',
    'Private\VPDLXreturn.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('PowerShell', 'Windows', 'Logging', 'DataLogging', 'DataLog',
                 'VirtualLog', 'OOP', 'Classes', 'VPDLX')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani/PowerShell.Mods'

        # ReleaseNotes of this module
        ReleaseNotes = @'
v1.01.00  (06.04.2026)
----------------------
Full architectural rewrite: function-based design replaced by a clean
class-based OOP architecture.

New classes (all registered as TypeAccelerators):
  [Logfile]
      .Write(level, message)          - append a single formatted log entry
      .Print(level, messages[])       - append multiple entries in one call
      .Read(line)                     - retrieve a specific line (1-based, clamped)
      .SoakUp()                       - retrieve complete log content as string[]
      .FilterByLevel(level)           - retrieve lines matching a specific log level
      .Reset()                        - clear all log data (irreversible)
      .Destroy()                      - unregister and dispose the instance
      .Info/Debug/Verbose/Trace/Warning/Error/Critical/Fatal(msg)  - shortcut write methods
      .GetDetails()                   - access the [FileDetails] companion object
      .IsEmpty()                      - returns $true if no entries exist
      .HasEntries()                   - returns $true if at least one entry exists
      .EntryCount()                   - returns the current number of entries

  [FileDetails]
      .GetCreated()                   - creation timestamp
      .GetUpdated()                   - last write/reset timestamp
      .GetLastAccessed()              - last read/filter timestamp
      .GetLastAccessType()            - type of the most recent interaction
      .GetEntries()                   - current entry count
      .GetAxcount()                   - total interaction counter since creation
      .ToHashtable()                  - all metadata as an ordered hashtable

  [FileStorage]
      .Contains(name)                 - check if a logfile name is registered
      .Get(name)                      - retrieve a Logfile instance by name
      .Count()                        - number of registered instances
      .GetNames()                     - array of all registered names

Infrastructure:
  VPDLXcore -KeyID appinfo            - module metadata
  VPDLXcore -KeyID storage            - [FileStorage] singleton
  VPDLXcore -KeyID export             - export format definitions (txt, csv, json, log)

Bugfix:
  Renamed Filter() -> FilterByLevel() in [Logfile].
  'filter' is a reserved PowerShell keyword that caused a parser error
  preventing the class file from loading.

Removed (replaced by class methods):
  CreateNewLogfile, WriteLogfileEntry, ReadLogfileEntry, ResetLogfile, DeleteLogfile

v1.00.00  (05.04.2026)
----------------------
Initial release - function-based virtual log file management.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
