#
# Module manifest for module 'PSAppCoreLib'
#
# Generated by: Praetoriani (a.k.a. M.Sczepanski)
# Generated on: 26/10/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSAppCoreLib.psm1'

# Version number of this module.
ModuleVersion = '1.00.00'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '12345678-1234-5678-9abc-123456789012'

# Author of this module
Author = 'Praetoriani (a.k.a. M.Sczepanski)'

# Company or vendor of this module
CompanyName = 'Praetoriani'

# Copyright statement for this module
Copyright = '(c) 2025 Praetoriani. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Collection of useful functions for PowerShell apps'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @('System.Drawing', 'System.Windows.Forms')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('WriteLogMessage', 'GetBitmapIconFromDLL')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all files packaged with this module
FileList = @('PSAppCoreLib.psm1', 'PSAppCoreLib.psd1', 'Public\WriteLogMessage.ps1', 'Public\GetBitmapIconFromDLL.ps1', 'README.md')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PowerShell', 'Logging', 'Icons', 'Utilities', 'AppDevelopment')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/praetoriani'

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 1.00.00 (Initial Release)
================================
- WriteLogMessage: Advanced logging function with timestamp and severity flags
- GetBitmapIconFromDLL: Extract and convert icons from DLL files to bitmaps
- Comprehensive error handling with standardized return objects
- Full English documentation and code comments
- Compatible with PowerShell 5.1+ and PowerShell Core
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
